//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPlenario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefonos
    {
        public int TelefonoID { get; set; }
        public int PersonaID { get; set; }
        public string Telefono { get; set; }
    
        public virtual Personas Personas { get; set; }
    }
}
